### ISSUE TITLE
Could you please share your code

### ISSUE THREAD

**Issue by Pang-0093** [kaiwang960112/CAFE#1]
Hi Kai Wang, CAFE is an amazing work, could you please share your code? Thank you very much.

**Comment by kaiwang960112** [comment]
***@***.***

Pangza ***@***.***>于2023年3月21日 周二10:33写道：

**Comment by kaiwang960112** [comment]
OK，欢迎邮件讨论交流。

Pangza ***@***.***>于2023年3月21日 周二10:55写道：

**Comment by kaiwang960112** [comment]
for protect the privacy of this guy, hhhh

**Comment by YXTong17** [comment]
Your work is very impressive! Could you please share the code for CAFE? Thank you very much.
My email is tyx1017@gmail.com

**Comment by zhongjian-zhang** [comment]
Your work is very impressive! Could you please share the code for CAFE? Thank you very much.
My email is [zhangzj@bupt.edu.cn](mailto:zhangzj@bupt.edu.cn)

**Comment by Lay-du** [comment]
Your work is very impressive! Could you please share the code for CAFE? Thank you very much.
My email is [du123570@gmail.com](mailto:du123570@gmail.com)
